title: Naveen Hari
url: "https://econaveenhari.github.io/naveenhari"
baseurl: ""

remote_theme: ankitsultana/researcher@gem

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  
markdown_extensions:
      - fontawesome_markdown

#tracking_id: 

footer: yes
footer_url: "https://econaveenhari.github.io/naveenhari"
footer_text: "Naveen Hari"

sass:
    style: compressed
    sass_dir: _sass
